docs : 오류 코드와 메시지 처리6
스프링은 폼에서 넘어온 필드값과 ModelAttribute의 매치되어야 할
필드의 타입이 맞지 않을경우 타입미스매치 오류를 발생한다.

[다음의 4가지 메시지 코드가 입력되어있다.]
typeMismatch.item.price
typeMismatch.price
typeMismatch.java.lang.Integer
typeMismatch

[코드가 선언되어있지 않기 때문에 default메시지가 출력된다.]
Failed to convert property value of type java.lang.String to required type
java.lang.Integer for property price; nested exception is
java.lang.NumberFormatException: For input string: "A"

[errors.properties에 아래의 메시지 코드를 추가해보면
 적용되는것을 확인해 볼 수 있다.]
typeMismatch.java.lang.Integer=숫자를 입력해주세요.
typeMismatch=타입 오류입니다.